### ISSUE TITLE
NTC table requirement

### ISSUE THREAD

**Issue by igorchertenkov** [eigenein/ntc-one-wire#1]
Is there any particular reason for using lookup table instead of formula? ATMega can do logarithm, there is no high speed or low energy requirements, so I wonder what happens if I insert a bit of math in adcToTemperature function.

**Comment by eigenein** [comment]
No particular reason, actually. I just thought: "why recalculate it each and every time when I can make a table and even verify it prior to flashing?"

So, I guess, nothing bad would happen.
